### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by ahsatha** [JamesCoyle/vue-icon#2]
The icon is not showing though the component renders correctly, it needs a viewBox default of `0 0 24 24` of course you can add the type prop

**Comment by JamesCoyle** [comment]
If you set the type prop to `mdi` it will set the size and viewbox defaults to match what Material Design Icons requires.

**Comment by ahsatha** [comment]
Yes, I know but don't you think this should be the default? It's a minor thing I know. And also the README doesn't show the possible values for the type prop

**Comment by JamesCoyle** [comment]
I don't want these components to be seen as just an mdi component so I don't really want to set a default that assumes the icon is on a 24x24 grid. If I were to set a default I think I'd maybe go for a 100x100 viewbox which makes all of the values of the path percentage values. At least that way an icon would show up by default and it would be clear you needed to adjust the viewbox. 

I'm thinking of creating a new repo just for the default icon size and viewbox data so it's easier for all of these components to update to support new icon packs. Then that repo can document the possible values and the icon repos can just link to it.

**Comment by ahsatha** [comment]
I see your point now, you are right I was looking from the mdi perspective since that's what I'm using. Closing this now.
