### ISSUE TITLE
how set size in percent

### ISSUE THREAD

**Issue by newbie78** [JamesCoyle/vue-icon#6]
thanx for a component but how i do this?

when i'm set size="50%" work fine but i'v got error - "Invalid prop: type check failed for prop "size". Expected Number with value NaN, got String with value "50%"." in console

**Comment by newbie78** [comment]
https://github.com/JamesCoyle/vue-icon/pull/7

**Comment by JamesCoyle** [comment]
Well spotted. Merged and released in [0.1.2](https://www.npmjs.com/package/@jamescoyle/vue-icon/v/0.1.2).
