### ISSUE TITLE
Create a new release on NPM

### ISSUE THREAD

**Issue by riker09** [JamesCoyle/vue-icon#8]
The version which is published on the NPM registry says `0.1.0` and was released 10 month ago. However, the fix #3b1d180ca14f74c1aaf1bc8294df85e0bb2e0c3d was implemented only 8 month ago and has not been released yet.

I ran into this on one of my projects and spent some time debugging this since I assumed it was one of my frequently made mistakes. Please consider releasing the fixed version to the NPM registry.

**Comment by JamesCoyle** [comment]
Sorry about that... must have slipped through the cracks. [New version](https://www.npmjs.com/package/@jamescoyle/vue-icon/v/0.1.1) is now available. Post a new issue if you find any problems with that release.
