### ISSUE TITLE
Substituting an array value in the path prop creates error in browser console

### ISSUE THREAD

**Issue by digitalmouse** [JamesCoyle/vue-icon#9]
Hi!

In a current Vue3 project, I am using the Material Design Icons (SVGs) via @mdi/js and rendering them with your 'vue-icon' component.

relevant parts of the script section:

    import SvgIcon from '@jamescoyle/vue-icon'
    import { mdiClockStart, mdiAlert } from '@mdi/js'
    
...and in the Vue template:

    <svg-icon type="mdi" :path="mdiClockStart"></svg-icon>

This renders perfectly as expected.

**BUT**, if I want to render icons dynamically from within a loop over a related id value (always a number), I start to hit a snag.   In the template I have:

    <div v-for="state in states" :key="state.id">
      <svg-icon type="mdi" :path="stations[state.id].icon"></svg-icon>
     </div>

and in the code, I have defined the array in data:

    data: () => ({
      stations: [
        { icon: 'mdiClockStart', iconStyle: 'color: green' },
        { icon: 'mdiAlert', iconStyle: 'color: red' }
      ]
    })

This looks all well and good, but the browser console keeps telling me:

> 15:56:15.232 vue.runtime.esm.js:6829 Error: <path> attribute d: Expected number, "mdiAlert"

...as if it tried to insert the actual SVG markup into the path, instead of just the name of the icon as in the static example above.

If I output the contents of that array with double curly braces, I get the string value from that .icon node as expected.  I thought it would just substitute the value into the :path prop, _just like you can do with the :style prop - or most any other v-bind prop._  But no luck.

I also tried using a function inside :path to pass the state id and return the mdi icon name, but that also failed.

Looking at the markup output I see that the icon is substituted with the icon's actual SVG data.   Which works fine for static declarations, as noted above.   In the dynamic code the icon name is not 'translated'.  I guess you never expected to handle dynamically generated values?  Or did I miss some basic Vue condition?

Any tips or hints or known work-a-rounds?  Feels like I am close, but have run out of ideas.

Thanks in advance!

**Comment by JamesCoyle** [comment]
The issue is with your stations array:
```
stations: [
  { icon: 'mdiClockStart', iconStyle: 'color: green' },
  { icon: 'mdiAlert', iconStyle: 'color: red' }
]
```

You are defining the icons as a string and then passing that string to the icon component so instead of receiving the SVG path as expected, the icon component receives the string `mdiClockStart`. 

To fix this simply define your stations array like so:

```
stations: [
  { icon: mdiClockStart, iconStyle: 'color: green' },
  { icon: mdiAlert, iconStyle: 'color: red' }
]
```

This will set the icon property to be the SVG path instead of the icon name string. Just make sure you're importing all of the icons from @mdi/js correctly.

**Comment by digitalmouse** [comment]
Makes perfect sense!  Thanks for responding!
